// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    partial class IspitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Chat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("A_ChatSobaID")
                        .HasColumnType("int");

                    b.Property<int?>("A_KorisnikID")
                        .HasColumnType("int");

                    b.Property<string>("Boja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nadimak")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("A_ChatSobaID");

                    b.HasIndex("A_KorisnikID");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("WebTemplate.Models.ChatSoba", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("imeSobe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maksBrojClanova")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ChatSoba");
                });

            modelBuilder.Entity("WebTemplate.Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("korisnickoime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("WebTemplate.Models.Chat", b =>
                {
                    b.HasOne("WebTemplate.Models.ChatSoba", "A_ChatSoba")
                        .WithMany()
                        .HasForeignKey("A_ChatSobaID");

                    b.HasOne("WebTemplate.Models.Korisnik", "A_Korisnik")
                        .WithMany()
                        .HasForeignKey("A_KorisnikID");

                    b.Navigation("A_ChatSoba");

                    b.Navigation("A_Korisnik");
                });
#pragma warning restore 612, 618
        }
    }
}
