// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    partial class IspitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Iznajmljivanje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<int?>("VoziloID")
                        .HasColumnType("int");

                    b.Property<int>("brojDana")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("VoziloID");

                    b.ToTable("Iznajmljivanjes");
                });

            modelBuilder.Entity("WebTemplate.Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("JMBG")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("brojDozvole")
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    b.Property<string>("ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Korisniks");
                });

            modelBuilder.Entity("WebTemplate.Models.Vozilo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PredjenaKilometraza")
                        .HasColumnType("int");

                    b.Property<int>("brojSedista")
                        .HasColumnType("int");

                    b.Property<int>("cenapodanu")
                        .HasColumnType("int");

                    b.Property<int>("godiste")
                        .HasColumnType("int");

                    b.Property<bool>("iznajmljen")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Vozilos");
                });

            modelBuilder.Entity("WebTemplate.Models.Iznajmljivanje", b =>
                {
                    b.HasOne("WebTemplate.Models.Korisnik", "Korisnik")
                        .WithMany("UgovorIznajmljivanja")
                        .HasForeignKey("KorisnikID");

                    b.HasOne("WebTemplate.Models.Vozilo", "Vozilo")
                        .WithMany("UgovorIznajmljivanja")
                        .HasForeignKey("VoziloID");

                    b.Navigation("Korisnik");

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("WebTemplate.Models.Korisnik", b =>
                {
                    b.Navigation("UgovorIznajmljivanja");
                });

            modelBuilder.Entity("WebTemplate.Models.Vozilo", b =>
                {
                    b.Navigation("UgovorIznajmljivanja");
                });
#pragma warning restore 612, 618
        }
    }
}
